# This workflow automates the build process for a Node.js project using Grunt.
# It is triggered on pushes and pull requests to the "develop" branch.
# The workflow supports multiple Node.js versions to ensure compatibility.
# For more information on using GitHub Actions, visit: https://docs.github.com/en/actions

name: Node.js with Grunt

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Enable caching for npm dependencies

      - name: Install Dependencies
        run: npm ci  # Clean install from package-lock.json

      - name: Run Grunt Build
        run: |
          npm run grunt -- --verbose  # Run Grunt with verbose output for better logging
